### PR TITLE
Created foundation entities for RAG dashboard. Implemented quick dashboard to unblock RAG-18 and RAG-19

### LINKED ISSUE #17: FOUNDATIONAL - Create module and entity model for RAG status dashboard
Create the following items so the RAG dashboard work can be completed.

Entity
* Name

Metric
* EntityFor
* Status (Red, Amber, Green)
* DateFor
* Comments

New module named RAG (this would be the folder structure and __init__.py)

EXPECTED OUTCOME
Working base for other stories created.

### PR DESCRIPTION
**Pull request by fritogotlayed**
### Issue
Fixes #17 

### Summary
* Created `models.py` with Entity and Metric entites
* Created controller and templates for the new RAG dashboard

### Testing
* Run available unit / integration tests. 
* Start app and poke around a bit
* Navigate to http://127.0.0.1:8000/rag/ to view the dashboard sample

### CODE REVIEW

**Comment by fritogotlayed** [comment]
:raising_hand: Ready for review. @jbarganier I apologize it took me so long to get this pull requested.

**Comment by jbarganier** [comment]
sorry, I must have over looked this. Just did review. looks okay to me. Ready for second review.

**Comment by MrsDbones** [comment]
@fritogotlayed Merge conflicts - please resolve

**Comment by naitp** [comment]
:snail: looking

**Comment by naitp** [comment]
there is a RAG Report example there.  I can't merge due to conflicts.

**Comment by fritogotlayed** [comment]
@jbarganier @MrsDbones @naitp I've rebased this but I haven't tested it yet. Please hold off on review until I can check it.

**Comment by fritogotlayed** [comment]
@jbarganier @MrsDbones @naitp Merge looks good to me. Sorry about that. I should have verified before I updated the branch in origin.

**Pull request merged**
