### PR TITLE
Now using dependency injection

### PR DESCRIPTION
**Pull request by fritogotlayed**
### Story
N/A

### Summary
Refactored the code to use dependency injection. This should make testing easier in the long run.

### Testing
* Delete app.db
* Spin up the application
* Register a user
* Logout
* Login

### CODE REVIEW

**Comment by jbarganier** [comment]
verified I was able to run the website and register, logout, login a new user successfully.
Peer review 1 good.
ready for peer review 2

**Comment by naitp** [comment]
:snail: :snail: :snail: working at 3 snailpower, I have reviewed this and confirmed it's goodness.  MERGE GOOD SIR!

**Comment by fritogotlayed** [comment]
@jbarganier @naitp Could one of you please merge this since it's been through two reviews?

**Comment by jbarganier** [comment]
done

**Pull request merged**
