### PR TITLE
removed recaptacha and redundant login from registration page

### LINKED ISSUE #27: Remove ReCaptcha and extra login link from Register page
On the new user registration page there is a ReCaptcha and "Login" link. Remove both of these items from the page. The "Login" link is redundant since the login link is also in the top nav area. The ReCaptcha is going to fail when the application is deployed to another location. Once this issue is solved it may be re-added.

Steps to Reproduce:
* Run application
* Click "Register" link in header

Below are the items which need to be removed (red arrow pointing to them)
image

### PR DESCRIPTION
**Pull request by jbarganier**
### Issue 
Fixes #27

### Summary
Removed redundant login link and recaptcha thingie from the *register user* page. Also fixed red squiggly on the user controller for werkzeug import.

### Testing
Open the register page via the top menu bar link. Verify that the Recaptcha interface is not present and there is only one login link on the page (redundant login after recaptcha removed.)

### CODE REVIEW

**Comment by fritogotlayed** [comment]
:eyes: Looking at this now

**Comment by fritogotlayed** [comment]
Changes look good to me. Ready for second review :+1:

**Comment by naitp** [comment]
:snail: reviewing

**Comment by naitp** [comment]
looks good to me too.  ready for merge. :+1:

**Pull request merged**
