### PR TITLE
Filtering now working on the RAG dashboard page.

### LINKED ISSUE #16: Create dashboard page showing RAG status data
**NOTE** The layout depicted here is just a rough draft. The implementer is encouraged to make any improvements needed. Discuss with the team as needed. This has a dependency on #17

image

EXPECTED OUTCOME
Page that displays the RAG status of entities in the DB.

### PR DESCRIPTION
**Pull request by fritogotlayed**
### Issue
Fixes #16

### Summary
* Updated JQuery, Bootstrap
* Added Datatables.net, dateTimePicker
* Created site.js to assist with all our javascript needs in the application.
* Added bower file to help track when updates are needed to various web frameworks.
* Updated RAG controller to filter properly based on the inputs provided by the filter section on the dashboard
* Misc. other things I'm sure I am forgetting. I apologize for the large commit...

### Testing
* Run available unit / integration tests. 
* Start app and poke around a bit
* Navigate to http://127.0.0.1:8000/rag/ to view the dashboard sample

### CODE REVIEW

**Comment by jbarganier** [comment]
Reviewed. Looks good to me. ready for second reviewer @naitp @MrsDbones

**Comment by naitp** [comment]
The apply button for the date filter is in an odd location. Imo, it should be closer to the From and To calendar boxes.

**Comment by fritogotlayed** [comment]
@naitp Peer Review feedback has been addressed. Ready for another review.

**Comment by naitp** [comment]
:snail: :eyes: looking now

**Comment by naitp** [comment]
I like the 'apply' button much more now.  Filtering does work, very responsive as well.  :+1:

**Pull request merged**
