### PR TITLE
Created dashboard and logout. Made base page adaptive to user being logged in or not.

### LINKED ISSUE #11: Create unauthenticated dashboard
details incoming. 

EXPECTED OUTCOME

### PR DESCRIPTION
**Pull request by fritogotlayed**
### Story
Fixes #11 

### Summary
* Created dashboard at http://127.0.0.1:8000/ for users
* Added `Register`, `Login` and `Logout` links to base page nav bar
* Created `Logout` method on user controller to handle user log out

### Testing
* Start application
* Register user
* Authenticate as user
* Log out of user

### CODE REVIEW

**Comment by fritogotlayed** [comment]
@jbarganier @naitp @MrsDbones @Samsanchezz This is probably closer to about 1/2 the size of a normal pull request. This is ready for review :smile_cat:

**Comment by naitp** [comment]
:snail: Checked it out.  
* Application started, had a default page and dashboard.
* Successfully registered a user
* Successfully logged in as said user
* Was able to logout

**Comment by fritogotlayed** [comment]
Thanks @naitp!

@Samsanchezz @jbarganier @MrsDbones This is ready for a second review.

**Comment by jbarganier** [comment]
I downloaded it
i saw the header change depending if I was logged in or not.
I logged out.
test passed.

**Pull request merged**
