### PR TITLE
Issue24 remove nickname unique constraint

### LINKED ISSUE #24: Registering a new user account with a non-unique nickname results in failure
Attempting to register a new user account with a nickname that matches an existing record in the database will cause a unique constraint failure to occur on the users_user.name column. 

? can we just remove the unique constraint on the name field?  It looks like the email address is what really needs to be unique.

### PR DESCRIPTION
**Pull request by jbarganier**
### Issue 
Fixes #24

### Summary
Modified the users model so that the nickname does not have a unique constraint.

### Testing
Create 2 accounts that have the same nickname, but different email addresses to demonstrate the unique constraint on nickname has been removed.

**Procedure**
* Delete app.db if if exists
* Run RAG application
* From Menu bar, select *Register* link and create a new account with:
    * NickName = "foo", Email Address =  "foo@foo.com"
* complete the remaining fields and click the *Register* button
* logout of the foo@foo.com account
* From the Register page, create a 2nd account with
    * NickName = "foo",  but with email  = "bar@bar.com"
* Complete the remaining fields and click the *Register* button
* if the new account is created with out error, test passes.

### CODE REVIEW

**Comment by fritogotlayed** [comment]
:eyes: Looking at this now

**Comment by fritogotlayed** [comment]
Changes look good to me. Ready for a second review :+1:

**Comment by MrsDbones** [comment]
Looking at this now

**Comment by MrsDbones** [comment]
Looks good.

**Pull request merged**
