### PR TITLE
Unit Test for site root now in place.

### PR DESCRIPTION
**Pull request by fritogotlayed**
### Issue
N/A

### Summary
Added tests for the site root controller. **NOTE** these tests are currently integration tests. Once it is figured out how to make them unit these tests should be modified. 

### Testing
* Execute tests and verify all pass
* When running unit tests, add the environment variable "RAG_CONFIG" with the value "test_config"

### CODE REVIEW

**Comment by MrsDbones** [comment]
Currently looking at this

**Comment by MrsDbones** [comment]
These changes look good to me.  Ready for second review.

**Comment by jbarganier** [comment]
working on 2nd review

**Comment by jbarganier** [comment]
Merging code

**Pull request merged**
